name: The Life of Pablo
favicon: null
layout_spectrum: 0.98443
typography_spectrum: 0.60537
title: the life of pablo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff8149'
    - '#080000'
    - '#ebe5d0'
    - '#5e2315'
    - '#ac6447'
  brandStrength: 1
  lightness: 0.6894191517494619
  saturation: 0.7960761452559382
  rhythmicContrast: 0.7114388376940042
purpose: []
